site_name: TransQuest

nav:
    - Home: index.md
    - TransQuest Architectures:
      - Sentence-level: architectures/sentence_level_architectures.md
      - Word-level: architectures/word_level_architecture.md
    - Examples:
      - Sentence-level: examples/sentence_level_examples.md
      - Word-level: examples/word_level_examples.md
    - Pre-trained Models:
      - Sentence-level: models/sentence_level_pretrained.md
      - Word-level: models/word_level_pretrained.md
    - Contact: contact.md
theme: material

icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/TharinduDR/TransQuest
repo_name: tharindudr/TransQuest
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem:
        smart_enable: all
extra:
  generator: false
